### ISSUE TITLE
Could not resolve ClientVersion

### ISSUE THREAD

**Issue by JonathanVil** [WolverinDEV/BungeeUtil#11]
I just installed BungeeUtil, and the console prints this line 2 times, whenever I try to view the server on the server list or try to join. I have tried both 1.8.9 and 1.11 versions and I get the same errors.

`Could not resolve ClientVersion for 315. Disconnecting client`
`Could not resolve ClientVersion for 315. Disconnecting client`

BungeeCord version: 1.11 (1205)
BungeeUtil version: 1.6.9

**Comment by WolverinDEV** [comment]
Can you please use version 2.0?

I think the protocoll-version 315 is the 1.11 and its not implemented in 1.6.9

Maybe i should change the handling of unknown protocoll versions....

**Comment by JonathanVil** [comment]
Tried using version 2.0, and now getting this error when loading:

![Error](https://i.gyazo.com/92df157d779d86b951fd86769aef5cf9.png)

**Comment by WolverinDEV** [comment]
do you use the standalone version?

If not you have to use this.

**Comment by JonathanVil** [comment]
Use what?

**Comment by WolverinDEV** [comment]
https://github.com/WolverinDEV/BungeeUtil/tree/jars/buildedJars/standalone

**Comment by JonathanVil** [comment]
Yes, I use the standalone version... BungeeUtil-2.0-SNAPSHOT on the BungeeCord server

**Comment by WolverinDEV** [comment]
Hmm okey? Thats a littlebit funny. I will test it but i thought its workling and i think a bunch of server using 2.0 and havnt this problem but i will take a look at that.

**Comment by WolverinDEV** [comment]
Hey,
in my last commit i improved the versions handling a littlebit (https://github.com/WolverinDEV/BungeeUtil/commit/83756a63d93020620619cab9dd10a97aebee5d9d). I will create a release soon.
