### ISSUE TITLE
Inventory 0 become inventory 99 after opening custom inv

### ISSUE THREAD

**Issue by HoverEpic** [WolverinDEV/BungeeUtil#13]
On login, if i open my player's inventory, it's window 0, but if i open a custom inventory, then reopen my player's inv and click inside, BungeeUtil recieve click on window 99 and doesn't forward packets to spigot.
Don't know witch side the problem is (but bungeeUtil play's with packets so i think the problem is from the plugin).

**Comment by HoverEpic** [comment]
Just find out it appear only with my custom inventory, not with the bu dev menu, i'll check my code.

**Comment by WolverinDEV** [comment]
Hmm okey thats funny :D Maybe can you send the code?
It could be my fault if i missed to change a boolean in a methode

**Comment by HoverEpic** [comment]
I've write an abstract for all my menus, i create each menu with
`player.openInventory(new dev.wolveringer.bungeeutil.inventory.Inventory(0, ""))`
then i set the title, the size and the content.
I close a menu with `player.closeInventory()` method.

**Comment by WolverinDEV** [comment]
hmm okey? Why did you first open an empty inventory an change the thinks after opening it?
Maybe first change the title or the slots and then open it?

**Comment by HoverEpic** [comment]
Just find something, in my menus, i change the content then update the menu, witch not re-center the cursor (so the inventory instance is always the same).
On yours, you close the old view, then create a new on and sent it to the player.

Here is a better example:

```
//display & refresh
public void draw()
{
    //build the inv if not already exist
    if (m_Player.getInventoryView() == null)
        m_Player.openInventory(new dev.wolveringer.bungeeutil.inventory.Inventory(45, "Main menu"));

    m_Player.getInventoryView().clear();
    
    //build or refresh process
    m_Player.getInventoryView().setItem(2, *some item*);
    
    //update the inv if open
    if (m_Player.isInventoryOpened())
        m_Player.getInventoryView().updateInventory();
}

//close
close()
{
    m_Player.closeInventory();
}
```

After a close everything works fine except  window 0 ><

**Comment by WolverinDEV** [comment]
hmm thats fucking funny :D
I dount know why this happend.

A little tip: You dont need to update the inventory if you set an item. It will automaticly update the slot.
If you have to redraw a bunch of slots than you can call the methode disableUpdate and after updating enableUpdate. (If you had done some changes it will update automaticly)

**Comment by HoverEpic** [comment]
I just find the problem, NEVER create an inventory with 0 slots AND empty name!

**Comment by WolverinDEV** [comment]
Ahh okey. I added a check for that here: https://github.com/WolverinDEV/BungeeUtil/commit/60e49f3084692bd35a0be2d491b9ffed595ce659
I will puish it as soon its possible. Currently github have some problem idk....
