### ISSUE TITLE
Gui is lagging in 2.1?

### ISSUE THREAD

**Issue by WolverinDEV** [WolverinDEV/BungeeUtil#19]
![](https://i.gyazo.com/e9b437dc70064a6ef90fb1bf9f896db1.gif)
(Original 2.1.1 (from updater))

I have plugin that add gui with plugin on bungeecord. And when i click to item i can move it(Visual). In version 2.0 all was good. i cant click to item. in 2.1.1 i have a time to move item.

(This post is moved from the issue #18, but this is a new issue)

**Comment by WolverinDEV** [comment]
Thanks for this issue :) I alredy regoniced that localy but i currently dont have a verry stong pc so i hoped its only locally. I will debug this and hopefully  fix will comeout today :)

**Comment by WolverinDEV** [comment]
okey well i found the course. I changed the order of an constructor and changed in the PacketPlayOutSetSlot the window id and the slot id.... im an ideot

**Comment by Leymooo** [comment]
Fixed. Thanks.
