### ISSUE TITLE
Repository url missing

### ISSUE THREAD

**Issue by CC007** [WolverinDEV/BungeeUtil#20]
In the wiki you specify a dependency, but you didn't specify the repository url. Therefore (since it doesn't seem to be in the default repos used by maven), the build fails because the dependency can't be found. Could you add the repo url to the wiki description?

**Comment by WolverinDEV** [comment]
Hey,
BungeeUtil is uploaded at the maven central repository.It should be accessable without an repro URL.

(https://oss.sonatype.org/#nexus-search;classname~BungeeUtil)

**Comment by CC007** [comment]
Oss.sonatype.org isn't a default repo for all Maven distributions. The one that comes with Netbeans for example still needs that repo to be added to the pom. Also, the one on sonatype is outdated. You are at version 2.1.2, but the repo only contains 2.0

**Comment by CC007** [comment]
Could you add it to central.maven.org and to mvnrepository too?

**Comment by WolverinDEV** [comment]
Yeah its an littlebit outated but nothink changed from the api methods :)
But i will think abount an private responsetory for BungeeUtil

**Comment by CC007** [comment]
Just a note that it should be possible to auto deploy new release versions using maven.

**Comment by WolverinDEV** [comment]
Yes,
but i releasen BungeeUtils 2.1 at holloday and i dond had my deploy key
