### ISSUE TITLE
Make BungeeUtil modular

### ISSUE THREAD

**Issue by CC007** [WolverinDEV/BungeeUtil#21]
I would really like it if I could get just the packet API in a plugin. I don't need (or want) the full plugin when all I need is an easy way to intercept packets. 

To fix this, you could make this plugin modular, where each module contains a specific functionality of the plugin. The nice thing about this is that server owners can still decide to use the full plugin containing all the modules, but they can also choose to only get the packet API.

**Comment by WolverinDEV** [comment]
Hey,
well your idear sound verry good and i alredy thought about that,
but its a lots of work to change the structure and also what is with maven shade and the minimalize option?
I think it dose a pretty good job and removes all unused classes. You also have the posibility to disable the Scoreboard and BossBar API in the config.

**Comment by CC007** [comment]
When shading the updater makes the server crash as it tries to download the new version inside my jar, which is not a folder obviously. Also, if another plugin uses your api, it would cause conflicts between the two, especially when the versions differ.

Could you help me with building your repo by the way? Your 2.1.2 version doesn't seem to be able to build on my computer, even though all dependencies are imported, For instance, an import of dev.wolveringer.terminal.string.ColoredChar cant be found because it is located in dev.wolveringer.string.ColoredChar. Also a getter and setter annotation are causing problems.

**Comment by WolverinDEV** [comment]
Hey,
Well i know i missed to deploy the Terminals update. You have to builkd TerminalUtils localy (https://gitlab.com/WolverinDEV/TerminalUtils.git)

Well i also thought about an modular structure, but its not mutch logic.
A lots of stuff is so depend each other well it isnt smat to extract this. Well i will add in the future the possibilities to disable all API's but it will still need all classes
