### ISSUE TITLE
Left & Right custom inventory click events

### ISSUE THREAD

**Issue by HoverEpic** [WolverinDEV/BungeeUtil#23]
I was planning a pull request for this but I've done loads of changes to be able to compile the project (mostly non UTF-8 strings & TerminalUtils imports).
Can you add the ClickType support in ItemStack object? I've already made some tests [here](https://github.com/HoverEpic/BungeeUtil/commit/00d85d81e5104ae6a269df5c08cf573774c2dc4f).

Thanks.

**Comment by WolverinDEV** [comment]
Hey,
i think you already can get the click type by the mode int (https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/main/java/dev/wolveringer/bungeeutil/item/ItemStack.java#L34-L36).
A class for the easy handling can you find here (https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/main/java/dev/wolveringer/bungeeutil/packets/PacketPlayInWindowClick.java#L17-L83)

PS: I saw that i could change the Click class to to somethink with more lombok stuff :)

Lovely
WolverinDEV

**Comment by HoverEpic** [comment]
Oh thanks, i was confused by [the packet format](http://wiki.vg/Protocol#Click_Window), where the mode and button are two different things.

**Comment by WolverinDEV** [comment]
Ahh okey :D Well i yust put this two thinks together :D
