### ISSUE TITLE
ItemMeta.setGlow(true) not working

### ISSUE THREAD

**Issue by HoverEpic** [WolverinDEV/BungeeUtil#24]
Hi, this time i have a TRUE issue (troll).
The setGlow(b) method in [CraftItemMeta.java](https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/main/java/dev/wolveringer/bungeeutil/item/meta/CraftItemMeta.java#L167) is'nt working in 1.11.2, a NBTTagCompound in the NBTTagList is required  to render the effect client side.

Here a working solution :

```
NBTTagList l_NBTTagList = new NBTTagList(); //create the list
l_NBTTagList.add(new NBTTagCompound()); //add a new compound
l_Item.getItemMeta().getTag().set("ench", l_NBTTagList); //apply the list
l_Item.getItemMeta().getTag().set("HideFlags", new NBTTagInt(1)); //hide the ench in lore
```

**Comment by WolverinDEV** [comment]
Did you looked at this line?
https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/main/java/dev/wolveringer/bungeeutil/item/meta/CraftItemMeta.java#L170
This is equal to this three lines
```java
NBTTagList l_NBTTagList = new NBTTagList(); //create the list
l_NBTTagList.add(new NBTTagCompound()); //add a new compound
l_Item.getItemMeta().getTag().set("ench", l_NBTTagList); //apply the list
```

Well i think the point in your code is the `HideFlags` tag.
Im not setting this and maybe the client requires this in the 1.11.2 to show the glow.

**Comment by HoverEpic** [comment]
The new NBTTagList create a new array but empty:
![without](https://cloud.githubusercontent.com/assets/3588249/22560755/107e633e-e976-11e6-9b24-d3047944dad7.png)

And with the NBTTagCompound in the NBTTagList:
![with](https://cloud.githubusercontent.com/assets/3588249/22560794/2395b1a2-e976-11e6-808b-da598f043a24.png)
(on the with the item is glowing but hard to see)

The hide flag tag is for not showing the details of the enchantment in the lore ([bitmask can be used for a lot of things](http://minecraft.gamepedia.com/Tutorials/Command_NBT_tags#Items))

**Comment by WolverinDEV** [comment]
Oh well you're tight :)
Well i will fix this :)
 Thanks for this bug
