### ISSUE TITLE
Allow server-list-pings of unsupported versions

### ISSUE THREAD

**Issue by Janmm14** [WolverinDEV/BungeeUtil#26]
Because bungeecord allows them too.

**Comment by WolverinDEV** [comment]
Haha,
well i alredy implemented a kick message when outdated clients joining.
Maybe i will ad this soon

**Comment by WolverinDEV** [comment]
Implemented -> https://github.com/WolverinDEV/BungeeUtil/commit/d642fa3a2f60d08b300b7ec301fd8491f5f54081 (Update comming soon)

**Comment by WolverinDEV** [comment]
Released with BungeeUtils 2.4.0
