### ISSUE TITLE
Sounds for 1.11 missing

### ISSUE THREAD

**Issue by physanus** [WolverinDEV/BungeeUtil#32]
The sounds for 1.11 are not available, only the 1.9 and 1.10 sounds are configured.

How to reproduce: Just use ProxiedPlayerUserConnection#playSound() (used in Player#playSound())
Ex: ((Player) BungeeCord.getInstance().getPlayer("Dinnerbone")).playSound(SoundEffect.UI_BUTTON_CLICK);

Where to fix: dev/wolveringer/bungeeutil/sound/SoundEffect.java

Probably it is just copying the old sounds and pasting them using the 1.11 BigClientVersion PLUS adding (maybe) newly added sounds (not sure about that one).

**Comment by WolverinDEV** [comment]
Hmm yeah i saw it.
Well im currently very busy so maybe (if you want) can you add the sounds locally and make a pr?
Well i think this should be the easiest think, or you wait some time than i will do this (But it maybe toake some weks)

~WolverinDEV

**Comment by physanus** [comment]
I will look into it once I got some time for it. In case you can do it yourself and I did not mention anything else in here, just go for it

**Comment by kaerns** [comment]
created a pull-request for it

**Comment by WolverinDEV** [comment]
I think essem2 did this work pretty good :D
Thank you and i think i could close this issue :)

**Comment by physanus** [comment]
Yeah, thank you very much for doing this
