### ISSUE TITLE
1.12 Players cant join

### ISSUE THREAD

**Issue by MrFlashGamer** [WolverinDEV/BungeeUtil#35]
I use git:Waterfall-Bootstrap:1.12-SNAPSHOT:9ba9237:115 and when i try to ping or join the Server i dont get response but in the console i become this: Invalid WarpedMinecraftDecoder parameters! Cant having an client without a handshake but with a version! I use BungeeUtil 2.4.3

**Comment by MrFlashGamer** [comment]
Dieses Problem tretet auch bei der aktuellen Bungeecord Version auf... Merke erst jetzt, dadurch dass ich erst jetzt mich durch dein Profil geklickt habe, dass du auch Deutsch bist xd

**Comment by kaerns** [comment]
1.12 wurde von mojang noch nicht veröffentlicht und snapshots/pre-releases werden auch normalerweise von waterfall/bungeecord nicht veröffentlicht. ich denke wolverinDEV wird das plugin frühestens mit dem offiziellen release updaten was frühestens nächste woche sein wird.

**Comment by WolverinDEV** [comment]
Hey,
Bist du auch zRedblood von SpigotMC?
Und ja ich unterstütze Minecraft 1.12 noch nicht. Momentan geht BungeeUtils nur von 1.8.X-1.11.X.
Ich werde versuchen so schnell wie möglich die 1.12 zu implementieren, da ich aber zurzeit wirklich kaum Zeit habe (Wegen RL und ner kleinen Developer anstellung) kann es leider sein das das Update vil etwas länger dauern kann

Update:
Alles aktuelles zu meinen entwicklungen gegen die 1.12 gibts hier:
https://github.com/WolverinDEV/BungeeUtil/tree/1.12-Pre

**Comment by MrFlashGamer** [comment]
Nein, das bin ich nicht xd Ah, okay gut zu wissen xd Ja dann downgrade ich mal den Bungee... Brauche sowieso ja kein 1.12 zurzeit :)

**Comment by WolverinDEV** [comment]
xD Jo bitte arbeite momentan gerade dran aber weiß nicht wie schnell ich alles testen kann. Momentan code ich nur nach nase :D 

PS:
Ich lasse dieses Issue mal offen bis ich die 1.12 Version released habe/das sie geht ::D

**Comment by MrFlashGamer** [comment]
Eh, ich kann auch nicht mit der 1.8.x Version joinen xd
Egal ob ich jetzt bei der Version ohne 1.12 bin oder nicht

**Comment by WolverinDEV** [comment]
Welche BungeeCord-Version?
Welche BungeeUtils version?
Gibts irgendwelche errors etc?

**Comment by MrFlashGamer** [comment]
Nur diese Ausgabe die ich gesendet habe. Ich habe einmal Bungeecord Build 1232 genutzt und einmal Watrerfall Build 121 und die BungeeUtils Version ist die Version 2.4.3, die die es auf Spigot zum Downloaden gibt. Und wenn ich halt versuch zu joinen bekomm ich nur ein Disconnected zurück

**Comment by WolverinDEV** [comment]
Builde doch einfach die neuste von git. Die sollte gehen, wenn nicht währe dies echt verwunderlich

**Comment by WolverinDEV** [comment]
Hubs verclickt

**Comment by MrFlashGamer** [comment]
Das hab ich bereits versucht jedoch fehlen mir dazu paar Dependencies: 
`Could not resolve dependencies for project dev.wolveringer:BungeeUtil:jar:2.4.3: The following artifacts could not be resolved: dev.wolveringer.bungee:bungeecord-api:jar:1.11-SNAPSHOT, dev.wolveringer.bungee:bungeecord-proxy:jar:1.11-SNAPSHOT, dev.wolveringer:TerminalUtils:jar:1.1: Could not find artifact dev.wolveringer.bungee:bungeecord-api:jar:1.11-SNAPSHOT in ossrh-snapshots (https://oss.sonatype.org/content/repositories/snapshots)`

**Comment by WolverinDEV** [comment]
Dürfte dich interessieren:
https://github.com/WolverinDEV/BungeeUtil/commit/2bda0170998aad32d0e936b8a1270396c568d0d0

Alles Dependencies findest du auf meinem GitHub profiel oder GitLab profiel :)

**Comment by physanus** [comment]
Hey. Ich hab ja keine Ahnung, was du da schaffst, aber auf der neuesten BungeeCord bekomm ich auch den `Invalid WarpedMinecraftDecoder parameters! Cant having an client without a handshake but with a version!` mit der 1.11.x...
Jedes Mal, wenn ich was mit deinem Util schaffen will, kommt ein neuer Fehler auf... nicht schön :/

Mit einem alten BC Build klappt es wunderbar. Danke ;)

**Comment by WolverinDEV** [comment]
Hey,
es ist ganz einfach :D 
Die momentan letzte hochgeladene BungeeUtil version auf SPigotMC geht nur von 1.8-1.11.
Du kannst dir eine Version für BungeeUtils 1.8-1.12 selbst von GitHub builden unter der breanch 1.12.
Diese Version included momentan aber nur das prerelease 5, da ich nicht alle prereleases implementieren werde und dies eigendlich auch nur eine vorbereitung auf den Offiziellen 1.12 Release ist :)

LG
Wolverin

**Comment by physanus** [comment]
Jau, Tatsache. War mir gar nicht klar, dass die 1.12 im offiziellen Rep entwickelt wird, aber okay, wenn dem so ist. Ich nehm's zurück, danke :D

**Comment by WolverinDEV** [comment]
Bitte :)

**Comment by WolverinDEV** [comment]
1.12 Minecraft support released :)
