### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Lenni0451** [WolverinDEV/BungeeUtil#38]
Hi,
Ich habe eine Idee für ein Feature, und zwar wäre es toll eine InputGui oder so zu haben wo der Nutzer einen Test eingeben kann und man diesen dann verwenden kann, z.B. Bei einer ban GUI kann man dann den Ban grund angeben.
Für die Frage wieso ich sowas nicht selbst mache ist die Antowrt simpel: Ich habe keine Ahnung wie das geht

**Comment by kaerns** [comment]
1. meinst wohl "Text" anstatt "Test"
2. fände sowas auch praktisch aber ich denke WolverinDev ist gerade zu beschäftigt dafür. Da müssen wir erstmal abwarten ^^


**Was ist ein "InputGUI"?**
_Mit InputGUI ist ein Anvil gemeint den man für einen Spieler öffnen kann und dieser kann dann ein Item umbenennen das schon in dem Inventar liegt. Beim schließen bekommt man im Programm dann den Namen des Items als String heraus._

PS an WolverinDev: ich antworte nur immer so schnell weil ich E-Mails über neue Antworten immer direkt auf mein Handy bekomm und wenn ich dazu was weiß schreib ichs sofort ^^

**Comment by Lenni0451** [comment]
Ja, ich meine Text ;)
Wenn ich schnell schreibe schreibe ich aus irgendwelchen gründen imer Test statt Text

**Comment by WolverinDEV** [comment]
https://github.com/WolverinDEV/BungeeUtil/tree/2.0/src/main/java/dev/wolveringer/bungeeutil/inventory/anvil?
:D

**Comment by Lenni0451** [comment]
Das habe ich auch schon gefunden, ich weiß blos nicht wie ich überprüfe ob das umbenannte Item geklickt wurde, der Rest ist kein Problem.

**Comment by WolverinDEV** [comment]
https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/main/java/dev/wolveringer/bungeeutil/packetlib/handler/DebugMenue.java#L311-L345

**Comment by Lenni0451** [comment]
Danke, dass ist genau das was ich gesucht habe. Ich werde es morgen dann ausprobieren
