### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by HoverEpic** [WolverinDEV/BungeeUtil#40]
Hi WolverinDev, i'm close to release my Minecraft network and i'm still using BungeeUtil for inventory menus, but i think the packet handling library is a bit eating My CPU. I can't test my infrastructure  without your plugin for now (everything is based on it ><). I have only BungeeUtil, a Redis library and my players manager plugin.

Here is some timings reports (with 10 -13 players):
https://hastebin.com/oqijitahix
https://hastebin.com/aferezuyem

Here is a screenshot of cpu (E5-2640 v4 @ 2.40GHz) monitoring for the proxy process, the 800% spik is 10 players connections.
![proxy-1376](https://user-images.githubusercontent.com/3588249/27797950-cfc706d2-600f-11e7-8316-5b10d4e4d2b5.png)

I'll try to monitor things with yourkit as soon as possible to check what is wrong.
I'm afraid that i can't handle more than 100 player on a BungeeCord server.

What do you think about my problème?

**Comment by WolverinDEV** [comment]
Hey,
well im verry confused about this report.
Okey well i know that BungeeUtil makes the packet pass through sending handling a little bit slower (decoding handling and encoding), but i never saw a so hight cpu usage. Well i took a look over the timings and i cant find any anomalies. Well i think the inventory click function with an avarange handling speed of 6ms is verry slow but this gots only called when a player is in a inventory view and is interacting with an item, and the "click()" methode gets called.

Well im personally shure that its possible to handle more than 100 players on one BungeeCord (Im speaking from experience. I also used BungeeUtils on a old German cracked Minecraft network with around 300/400 Users (but its got now a littlebit smaler). Currently the have only one BungeeCord with around 50/100 Users and BungeeUtil is there a core depend plugin for the System and i think all works find there (im not working therer anymore so i have to trust some reports ;)). You can trie it by your self: EpicPvP.eu (the best test object is the report menue (just type /report in the chat). The full Menue is coded with BungeeUtils)).


PS: Sorry for my bnad english, but i hope you're able to understand all

**Comment by kaerns** [comment]
the timings might be so slow because something else is eating up CPU and don't let enough for bungeeutil.
i know that bungeecord itself need much cpu but the provided numbers are just too high for only bungeeutil & bungeecord usage.

**Comment by HoverEpic** [comment]
Thanks @WolverinDEV @essem2, i'll try to monitor the proxy with a profiler today.

Edit: just find that the CachedPacketCreator use a lot of CPU, I've disabled packet caching with `-Dbungeeutil.packet.no_cache=true`, visualy better performance in local env, still investigating.

**Comment by WolverinDEV** [comment]
Hey,
well im a littlebit suprised that the cached packet creator takes so "mutch" cpu.
Well the cached packet creator just takes the used class instances and resets them and reuses them.
The advantage of this should be that the javas gc dont have so mutch work and the gc pauses are less time intensive.
Well im verry interisted about the result of your new test with the disabled cached packet creator.

**Comment by HoverEpic** [comment]
I discover i have other problems in my players management system (player lost connection but is kept in memory & always connected on Spigot side), that probably was a point of my lag on proxy, i'm still searching for new bottlenecks (in my system).
Here is a 120 player (bot attack) on my network, timings report : https://hastebin.com/cemiyexica
with no open inventory. i'll try to make the bot open inventory & click to test it in real conditions.
I'll try to reactivate the CachedPacketCreator tomorrow and take 2 timings reports in same conditions, but it's a bit difficult to make test while rushing lasts features.

**Comment by WolverinDEV** [comment]
Well so the high cpu useage dosnt come from BungeeUtils?
Wenn this are good news :D 

Well i took a look over the timings report and i think BungeeUtils done a pretty god job :D 
I dont know how the performance looked likes in real time but i think that BungeeUtil dont realy decreses your performance.

**Comment by HoverEpic** [comment]
Yesterday we'made a real sized, real players tests, and at 100 players, the dedicated server 100% CPU on all of the 40 threads. We have collected tons of logs and find what possibly cause CPU usage on bungeecord : our storage lib!
We use a "in memory distributed storage", each bungeecord & spigot is a server member of the cluster, who can put / get whatever it want's in it (like players data, lobby list, stats).
The problem is when you close a node, the cluster internaly reorganize it's data and with 20 nodes it cause huge lags on other nodes =).
I think that's it, BungeeUtils is NOT the cause of lags in my case.
Thanks

**Comment by WolverinDEV** [comment]
Hey,
thanks for the report anyway.
Well i hope you can fix your bug and have a nice experience with BungeeUtil :D
