### ISSUE TITLE
AnvilGUI bug

### ISSUE THREAD

**Issue by SpraxDev** [WolverinDEV/BungeeUtil#45]
- Using latest Version from Spigot (2.5) (Auto-Updater updated to 2.5.2 [?])

My Code:
```
AnvilGui anvilGUI = new AnvilGui((Player) p);

anvilGUI.setBackgroundItem(ItemBuilder.create(Material.APPLE));
anvilGUI.setOutputItem(ItemBuilder.create(Material.NAME_TAG).name("§2Spieler melden").build());
anvilGUI.setBackgroundMessage("Kommentar");
anvilGUI.setColorPrefix("");

anvilGUI.addListener(new AnvilGuiListener() {
	@Override
	public void onMessageChange(AnvilGui gui, String msg) {
	}

	@Override
	public void onConfirmInput(AnvilGui gui, String msg) {
		p.sendMessage(TextComponent.fromLegacyText(msg));
	}

	@Override
	public void onClose(AnvilGui gui) {
		p.sendMessage(TextComponent.fromLegacyText(Main.prefix_player + "§cDer Vorgang wurde abgebrochen!"));
	}
});

anvilGUI.open();
```

Bug:
When I delete the Text with 'Backspace' it removes the whole text (not the bug). But it adds a Arrow (UTF-8)

Video:
https://youtu.be/Rt8NJdw0jXg

**Comment by WolverinDEV** [comment]
Hey,
which os are you using? And whats your default encoding?

**Comment by SpraxDev** [comment]
- The Server is running on Debian 8 (latest-stable)
- Java 8 131 (Should be latest Updated)
- Default encoding is UTF-8 (Eclipse-Project)

**Comment by WolverinDEV** [comment]
Hmm this is funny.
Are you shading BungeeUtils or using the standalone jar?

**Comment by SpraxDev** [comment]
I'm using the Standalone jar.

I used the jar from the Spigot-Page and moved it to my Waterfall-Plugin-Directory

**Comment by WolverinDEV** [comment]
Is this issue still alive?

**Comment by SpraxDev** [comment]
I can't tell. Sorry. I stopped using BungeeUtil and used a Spigot Plugin instead. I remember having some trouble because of 1.8-1.11.2 when recoding (but not sure if my fault or BungeeUtil).

**Comment by WolverinDEV** [comment]
okey ;(
