### ISSUE TITLE
1.12.1 Support

### ISSUE THREAD

**Issue by kaerns** [WolverinDEV/BungeeUtil#47]
Mojang released 1.12.1 two days ago with an important bugfix. 
https://minecraft.net/de-de/article/minecraft-1121-released
Bungeecord (and spigot) got updated on the same day.
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12-1.262238/
Due to some protocol changes BungeeUtil is not compatible. 
http://wiki.vg/Protocol_History#1.12.1 (17w31a contains all changes, after this they just incremented the version).

Edit: No need to answer this, its just a reminder. Just close it when its done.

**Comment by WolverinDEV** [comment]
Minecraft 1.12.1 Support implemented (want just changing the version number (had to remapp some packets))
