### ISSUE TITLE
Error on server start

### ISSUE THREAD

**Issue by player04** [WolverinDEV/BungeeUtil#49]
when i start server, it throws exception with class loading.
java.lang.NoClassDefFoundError: dev/wolveringer/configuration/Configuration
i think error is here:
https://github.com/WolverinDEV/BungeeUtil/blob/b977e949f48ebc5482357e6e3ff1945d5bed8bd4/src/main/java/dev/wolveringer/bungeeutil/Configuration.java#L8
and yes, sorry for my bad English)
P.S. using BungeeUtil 2.5.5

**Comment by WolverinDEV** [comment]
Hey,
i guass that youre using the jar and not the standalone build , right?
The jar contains only the compiled source of BungeeUtil without any libraries. You have to install them separately.
You also can download BungeeUtil with libraries included from here https://github.com/WolverinDEV/BungeeUtil/tree/jars/buildedJars/standalone

**Comment by player04** [comment]
Oh, yes
Thank you!
