### ISSUE TITLE
BungeeUtil keeps crashing my server. 

### ISSUE THREAD

**Issue by riyrus** [WolverinDEV/BungeeUtil#50]
Bungee Util Version - 2.5
Bungee cord Version - 1.8x
When does this error happen - When bungeeutil try's to load on my Proxy Server For Bungeecord.
I have a log for the error Here it is.
03.09 14:18:01 [Multicraft] Looks like a crash, check the server console. Return value: 255
03.09 14:18:01 [Multicraft] Received kill command
03.09 14:18:00 [Multicraft] Stopping server!
03.09 14:18:00 [Multicraft] Restarting crashed server in 2.0 seconds
03.09 14:18:00 [Multicraft] Server shut down (starting)
03.09 14:18:00 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [1%]
Loading BungeeUtil >> Restarting bungeecord [2%]
Loading BungeeUtil >> Restarting bungeecord [3%]
Loading BungeeUtil >> Restarting bungeecord [4%]
Loading BungeeUtil >> Restarting bungeecord [5%]
Loading BungeeUtil >> Restarting bungeecord [6%]
Loading BungeeUtil >> Restarting bungeecord [7%]
Loading BungeeUtil >> Restarting bungeecord [8%]
Loading BungeeUtil >> Restarting bungeecord [9%]
Loading BungeeUtil >> Restarting bungeecord [10%]
Loading BungeeUtil >> Restarting bungeecord [11%]
Loading BungeeUtil >> Restarting bungeecord [12%]
Loading BungeeUtil >> Restarting bungeecord [13%]
Loading BungeeUtil >> Restarting bungeecord [14%]
Loading BungeeUtil >> Restarting bungeecord [15%]
Loading BungeeUtil >> Restarting bungeecord [16%]
Loading BungeeUtil >> Restarting bungeecord [17%]
Loading BungeeUtil >> Restarting bungeecord [18%]
Loading BungeeUtil >> Restarting bungeecord [19%]
Loading BungeeUtil >> Restarting bungeecord [20%]
Loading BungeeUtil >> Restarting bungeecord [21%]
Loading BungeeUtil >> Restarting bungeecord [22%]
Loading BungeeUtil >> Restarting bungeecord [23%]
Loading BungeeUtil >> Restarting bungeecord [24%]
Loading BungeeUtil >> Restarting bungeecord [25%]
Loading BungeeUtil >> Restarting bungeecord [26%]
Loading BungeeUtil >> Restarting bungeecord [27%]
Loading BungeeUtil >> Restarting bungeecord [28%]
Loading BungeeUtil >> Restarting bungeecord [29%]
Loading BungeeUtil >> Restarting bungeecord [30%]
Loading BungeeUtil >> Restarting bungeecord [31%]
Loading BungeeUtil >> Restarting bungeecord [32%]
Loading BungeeUtil >> Restarting bungeecord [33%]
Loading BungeeUtil >> Restarting bungeecord [34%]
Loading BungeeUtil >> Restarting bungeecord [35%]
Loading BungeeUtil >> Restarting bungeecord [36%]
Loading BungeeUtil >> Restarting bungeecord [37%]
Loading BungeeUtil >> Restarting bungeecord [38%]
Loading BungeeUtil >> Restarting bungeecord [39%]
Loading BungeeUtil >> Restarting bungeecord [40%]
Loading BungeeUtil >> Restarting bungeecord [41%]
Loading BungeeUtil >> Restarting bungeecord [42%]
Loading BungeeUtil >> Restarting bungeecord [43%]
Loading BungeeUtil >> Restarting bungeecord [44%]
Loading BungeeUtil >> Restarting bungeecord [45%]
Loading BungeeUtil >> Restarting bungeecord [46%]
Loading BungeeUtil >> Restarting bungeecord [47%]
Loading BungeeUtil >> Restarting bungeecord [48%]
Loading BungeeUtil >> Restarting bungeecord [49%]
Loading BungeeUtil >> Restarting bungeecord [50%]
Loading BungeeUtil >> Restarting bungeecord [51%]
Loading BungeeUtil >> Restarting bungeecord [52%]
Loading BungeeUtil >> Restarting bungeecord [53%]
Loading BungeeUtil >> Restarting bungeecord [54%]
Loading BungeeUtil >> Restarting bungeecord [55%]
Loading BungeeUtil >> Restarting bungeecord [56%]
Loading BungeeUtil >> Restarting bungeecord [57%]
Loading BungeeUtil >> Restarting bungeecord [58%]
Loading BungeeUtil >> Restarting bungeecord [59%]
Loading BungeeUtil >> Restarting bungeecord [60%]
Loading BungeeUtil >> Restarting bungeecord [61%]
Loading BungeeUtil >> Restarting bungeecord [62%]
Loading BungeeUtil >> Restarting bungeecord [63%]
Loading BungeeUtil >> Restarting bungeecord [64%]
Loading BungeeUtil >> Restarting bungeecord [65%]
Loading BungeeUtil >> Restarting bungeecord [66%]
Loading BungeeUtil >> Restarting bungeecord [67%]
Loading BungeeUtil >> Restarting bungeecord [68%]
Loading BungeeUtil >> Restarting bungeecord [69%]
Loading BungeeUtil >> Restarting bungeecord [70%]
Loading BungeeUtil >> Restarting bungeecord [71%]
Loading BungeeUtil >> Restarting bungeecord [72%]
Loading BungeeUtil >> Restarting bungeecord [73%]
Loading BungeeUtil >> Restarting bungeecord [74%]
Loading BungeeUtil >> Restarting bungeecord [75%]
Loading BungeeUtil >> Restarting bungeecord [76%]
Loading BungeeUtil >> Restarting bungeecord [77%]
Loading BungeeUtil >> Restarting bungeecord [78%]
Loading BungeeUtil >> Restarting bungeecord [79%]
Loading BungeeUtil >> Restarting bungeecord [80%]
Loading BungeeUtil >> Restarting bungeecord [81%]
Loading BungeeUtil >> Restarting bungeecord [82%]
Loading BungeeUtil >> Restarting bungeecord [83%]
Loading BungeeUtil >> Restarting bungeecord [84%]
Loading BungeeUtil >> Restarting bungeecord [85%]
Loading BungeeUtil >> Restarting bungeecord [86%]
Loading BungeeUtil >> Restarting bungeecord [87%]
Loading BungeeUtil >> Restarting bungeecord [88%]
Loading BungeeUtil >> Restarting bungeecord [89%]
Loading BungeeUtil >> Restarting bungeecord [90%]
Loading BungeeUtil >> Restarting bungeecord [91%]
Loading BungeeUtil >> Restarting bungeecord [92%]
Loading BungeeUtil >> Restarting bungeecord [93%]
Loading BungeeUtil >> Restarting bungeecord [94%]
Loading BungeeUtil >> Restarting bungeecord [95%]
Loading BungeeUtil >> Restarting bungeecord [96%]
Loading BungeeUtil >> Restarting bungeecord [97%]
Loading BungeeUtil >> Restarting bungeecord [98%]
Loading BungeeUtil >> Restarting bungeecord [99%]
Loading BungeeUtil >> Restarting bungeecord [100%]
>
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at dev.wolveringer.bungeeutil.plugin.Main.onEnable(Main.java:76)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at dev.wolveringer.bungeeutil.plugin.updater.UpdaterV2.update(UpdaterV2.java:234)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at dev.wolveringer.bungeeutil.plugin.updater.UpdaterV2.updateTo(UpdaterV2.java:282)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at java.net.URL.openStream(URL.java:1045)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at java.security.AccessController.doPrivileged(Native Method)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] SEVERE java.io.FileNotFoundException: https://github.com/WolverinDEV/BungeeUtil/raw/jars/buildedJars/standalone/BungeeUtil-2.5.5c.jar
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] INFO [BungeeUtil][DEBUG] Cant download update. Exception:
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] BungeeUntil An error happend while downloading the update.
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord [0%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Restarting bungeecord
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Update failed.
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Update found. Updating.
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Update found. Updating.
03.09 14:17:59 [Server] BungeeUntil Starting to download the update (https://github.com/WolverinDEV/BungeeUtil/raw/jars/buildedJars/standalone/BungeeUtil-2.5.5c.jar) to /plugins/BungeeUtil/updater/BungeeUtils-v2.5.5.download
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Update found. Updating.
03.09 14:17:59 [Server] BungeeUntil Updating from 2.5 to 2.5.5                 
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Update found. Updating.
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Update found. Updating.
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Update found. Updating.
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [100%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [99%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [98%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [97%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [96%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [95%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [94%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [93%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [92%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [91%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [90%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [89%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [88%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [87%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [86%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [85%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [84%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [83%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [82%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [81%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [80%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [79%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [78%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [77%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [76%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [75%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [74%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [73%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [72%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [71%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [70%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [69%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [68%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [67%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [66%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [65%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [64%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [63%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [62%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [61%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [60%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [59%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [58%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [57%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [56%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [55%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [54%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [53%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [52%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [51%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [50%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [49%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [48%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [47%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [46%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [45%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [44%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [43%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [42%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [41%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [40%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [39%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [38%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [37%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [36%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [35%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [34%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [33%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [32%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [31%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [30%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [29%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [28%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [27%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [26%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [25%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [24%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [23%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [22%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [21%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [20%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [19%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [18%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [17%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [16%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [15%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [14%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [13%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [12%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [11%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [10%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [9%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [8%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [7%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [6%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [5%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [4%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [3%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [2%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [1%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data [0%]
03.09 14:17:59 [Server] INFO Loading BungeeUtil >> Loading update data
03.09 14:17:57 [Server] BungeeUntil Fetching update data.         
03.09 14:17:57 [Server] INFO Loading BungeeUtil >> Loading update data
03.09 14:17:57 [Server] INFO Loading BungeeUtil >> Loading update datanull[42G42Gnullnull
03.09 14:17:57 [Server] INFO Loading BungeeUtil >> Loading update datanull
03.09 14:17:57 [Server] BungeeUntil Detected Minecraft proxy type: BUNGEECORD
03.09 14:17:57 [Server] INFO Enabled plugin cmd_find version git:cmd_find:1.9-SNAPSHOT:f265f7c:1136 by SpigotMC
03.09 14:17:57 [Server] INFO Enabled plugin reconnect_yaml version git:reconnect_yaml:1.9-SNAPSHOT:f265f7c:1136 by SpigotMC
03.09 14:17:57 [Server] WARNING Forced host server pvp is not defined
03.09 14:17:57 [Server] INFO Loaded plugin cmd_list version git:cmd_list:1.9-SNAPSHOT:f265f7c:1136 by SpigotMC
03.09 14:17:57 [Server] INFO Loaded plugin cmd_send version git:cmd_send:1.9-SNAPSHOT:f265f7c:1136 by SpigotMC
03.09 14:17:57 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.9-SNAPSHOT:f265f7c:1136 by SpigotMC
03.09 14:17:57 [Server] INFO Loaded plugin Banmanager version 1.0.1-INDEV by shawlaf
03.09 14:17:57 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.9-SNAPSHOT:f265f7c:1136 by SpigotMC
03.09 14:17:57 [Server] INFO Loaded plugin BungeeUtil version 2.5 by WolverinDEV
03.09 14:17:57 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.9-SNAPSHOT:f265f7c:1136 by SpigotMC
03.09 14:17:57 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.9-SNAPSHOT:f265f7c:1136 by SpigotMC
03.09 14:17:57 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
03.09 14:17:57 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
03.09 14:17:57 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
03.09 14:17:57 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
03.09 14:17:57 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
03.09 14:17:57 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
03.09 14:17:57 [Server] INFO Epoll is working, utilising it!
03.09 14:17:57 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
03.09 14:17:57 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:f265f7c:1136
03.09 14:17:57 [Server] INFO Using native code compressor
03.09 14:17:57 [Server] INFO Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
03.09 14:17:57 [Server] INFO Could not load native library: /tmp/bungeecord-native-cipher9030773397658009574.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by kaerns** [comment]
it seems like the updater fails. please update manually to the newest build: 2.5.5
https://github.com/WolverinDEV/BungeeUtil/tree/jars/buildedJars/standalone

@WolverinDEV here is the issue: 2.5.5c is not a valid version. 
03.09 14:17:59 [Server] SEVERE java.io.FileNotFoundException: https://github.com/WolverinDEV/BungeeUtil/raw/jars/buildedJars/standalone/BungeeUtil-2.5.5c.jar

**Comment by WolverinDEV** [comment]
@essemX 
Thanks to you man you helped me a lot :)

@riyrus 
Bug fixed. Thanks for your submit :)
