### ISSUE TITLE
1.12.2 Support

### ISSUE THREAD

**Issue by kaerns** [WolverinDEV/BungeeUtil#51]
Just a little reminder that 1.12.2 has been released with the protocol number 340 and some protocol changes.

Useful links:
BungeeCord Update: https://github.com/SpigotMC/BungeeCord/commit/0eaabdf5ca6dddd2bcdd57b77d3d02bc4967105e
Protocol Changes:
Keepalive (Clientbound and Serverbound) changed keep Alive ID from VarInt to Long
Source: http://wiki.vg/index.php?title=Protocol&type=revision&diff=13363&oldid=13339

**Comment by kaerns** [comment]
also want to mention that issue #44 seems resolved and pullrequest #42 could still be merged, if something is wrong or need improvment for it then please say it.

**Comment by WolverinDEV** [comment]
Hey,
well im verry happy about your huge participation.
I will implement the Minecraft 1.12.2 support as soon as possible, but i think with your help its a lots easier.
I will also merge your pr. (Forgive me but i forgot it :D)

**Comment by kaerns** [comment]
thanks, i just want to support you as much as possible as i know that you are busy currently.
idk if this is also for bungeeutil relevant:
https://github.com/SpigotMC/BungeeCord/commit/61cb2df9f359fd56d8ec9f2946adb419dccace63

**Comment by WolverinDEV** [comment]
https://github.com/WolverinDEV/BungeeUtil/commit/d1700930928a8947b5f714258f0e4d1a8d74e296

-- Version support Implemented.
Thank you @essemX
