### ISSUE TITLE
BungeeUtils Bug

### ISSUE THREAD

**Issue by HydraDE** [WolverinDEV/BungeeUtil#54]
BungeeUtil Version: 2.6
BungeeCord Version: git:BungeeCord-Bootstrap:1.12-SNAPSHOT:9fd9843:1287
When this error happens: When the BungeeCord Server started
Computer System: Debian 9.2
Error: 
javassist.NotFoundException: net.md_5.bungee.UserConnection
20:43:55 [SCHWERWIEGEND] at javassist.ClassPool.get(ClassPool.java:436)
20:43:55 [SCHWERWIEGEND] at javassist.ClassPool.getCtClass(ClassPool.java:467)
20:43:55 [SCHWERWIEGEND] at dev.wolveringer.bungeeutil.injector.InjectFiles.inject(InjectFiles.java:38)
20:43:55 [SCHWERWIEGEND] at dev.wolveringer.bungeeutil.BungeeUtil.inject(BungeeUtil.java:121)
20:43:55 [SCHWERWIEGEND] at dev.wolveringer.bungeeutil.plugin.Main.onEnable(Main.java:137)
20:43:55 [SCHWERWIEGEND] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
20:43:55 [SCHWERWIEGEND] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:266)
20:43:55 [SCHWERWIEGEND] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
20:43:55 [SCHWERWIEGEND] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by kaerns** [comment]
do you use a modifyed version of bungeecord or any other plugin that modifyes bungeecord?

**Comment by HydraDE** [comment]
No

**Comment by essemX** [comment]
ok i will look into it... next year xD (23:11 here)

**Comment by HydraDE** [comment]
:D

**Comment by kaerns** [comment]
Erst jetzt bemerkt das im log was auf deutsch stand xD
Also hab mal kurz rein geschaut aber kann keinen code-fehler identifizieren. Scheint aus irgendwelchen gründen net.md_5.bungee.UserConnection nicht im default class pool zu finden was auf einen modifizierten bungee hinweist aber woher das genau kommt kann ich nicht sagen. Da müsste @WolverinDEV mal reinschauen, eveltuell könnte man für einen solchen fehler eine notfallroutine einbauen welche überprüft ob die class vorhanden ist und wenn nicht nochmal speziell danach sucht oder einen informativeren fehler ausgibt.


Zeile mit dem Fehler: https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/main/java/dev/wolveringer/bungeeutil/injector/InjectFiles.java#L38

**Comment by WolverinDEV** [comment]
Hey,
könntest du vil. deine BungeeCord.jar mal hochladen?
Ich könnte es dann bei mir mal local testen, aber ich glaube immernochnicht wirklich das das ein essenzieller Fehler in BungeeUtils ist :)

**Comment by HydraDE** [comment]
Hier ist der Downloadlink: https://www.file-upload.net/download-12898449/BungeeCord.jar.html

**Comment by WolverinDEV** [comment]
Hmm okey. Es verwundert mich, dass es bei dir nicht klappt.

Ich habe mal einen BungeeCord mit deiner Jar aufgesetzt und alles 
funktionierte einbandfrei: https://imgur.com/a9kxj1v.

Hast du BungeeUtils schonmal ohne weitere Plugins versucht? (Nur zum 
testzwecke ob es dann geht)

**Comment by HydraDE** [comment]
Ich hab mal ein Video gemacht -> https://youtu.be/haAVMgHSoWU

**Comment by WolverinDEV** [comment]
Hey,
kannst du mal dieses Setup außprobieren?
https://workupload.com/file/hQkmU4g
(PS Bei mir local gehts)

**Comment by HydraDE** [comment]
Das hat funktioniert. Hast du ne andere BungeeCord Version genutzt?

**Comment by WolverinDEV** [comment]
Ne habe ich nicht. Ich habe deine Jar genommen (nur umbenant)
Kannst gerne den SHA1 Hash vergleichen :)
Naja ich denke problem gelößt oder?

**Comment by HydraDE** [comment]
Ja, danke für den kompetenten Support. Ich schreibe dir noch ne Bewertung auf SpigotMC :D
