### ISSUE TITLE
BungeeUtil Inventory API

### ISSUE THREAD

**Issue by cluedo10** [WolverinDEV/BungeeUtil#55]
Hey,

I downloaded and integraded your API in my Maven Project where i tried to create an Inventory at BungeeCord all is working but when i trie to set the itemmeta i doesnt work it shows up the dialog with the message(The Method setItemMeta(ItemMeta) is undefined for the Type Item) i also tried to change the Type of the Item to ItemStack but it also show up the same dialog(The Method setItemMeta(ItemMeta) is undefined for the Type ItemStack)

I hope you can help me.

Thank you.

**Comment by WolverinDEV** [comment]
Hello,
you dont need to apply the ItemMeta.
If you changed the ItemMeta it saved automatically and in case of an open inventory get updated.

**Comment by cluedo10** [comment]
Okay thank you, one more question how to setFlags ? It is red underlined

**Comment by WolverinDEV** [comment]
setFlags? :D I dont know what you mean :)

**Comment by kaerns** [comment]
i think he means this method which is not available in bungeeutil
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#addItemFlags-org.bukkit.inventory.ItemFlag...-

**Comment by cluedo10** [comment]
Yes, I mean that, it's a pity that there is not something in bungeeutil

**Comment by WolverinDEV** [comment]
Hmm I guess this is something that I missed to update in in the past.
May cluedo10 you can implement it by yourself and create a PR? 🤣

**Comment by cluedo10** [comment]
java.lang.NoSuchMethodError: dev.wolveringer.bungeeutil.inventory.Inventory.getItem(I)Ldev/wolveringer/bungeeutil/item/ItemStack;

Get this Error from your Plugin :O

My Method:
for(int i = 0; i < ids.getSlots(); i++) {
if(ids.getItem(i) != null) {
continue;
} else {


//ids = Inventory

**Comment by kaerns** [comment]
hast du BungeeUtil korrekt im buildpath eingegeben und auf dem Server vorhanden?
Hast du BungeeUtil als dependcy angegeben?

**Comment by cluedo10** [comment]
Das  steht in meiner pom.xml:

```
<dependency>
			<groupId>dev.wolveringer</groupId>
			<artifactId>BungeeUtil</artifactId>
			<version>2.0-SNAPSHOT</version>
			<scope>provided</scope>
</dependency>
```

Und am Server ist das Plugin auch vorhanden und als dependcy auch eingetragen

**Comment by cluedo10** [comment]
PS: Wenn ich den Command eingebe, werde ich auch sofort gekickt

**Comment by kaerns** [comment]
mir fällt jetzt erst auf das ich vorhin ausversehen auf deutsch geschrieben hab xD
egal kenn mich mit maven ned so aus, ich füg die bungeeutil immer in den buildpath hinzu. ausserdem hast du die standalone oder welche version hast du auf dem server?

**Comment by cluedo10** [comment]
Am Server habe ich die 2.6 Version da es mit der 2.0 nicht klappt

**Comment by kaerns** [comment]
nutze bitte für beide 2.6

**Comment by cluedo10** [comment]
Für 2.6 gibt es aber leider kein Maven Repository :/

**Comment by cluedo10** [comment]
Hat doch geklappt danke dir trotzdem für deine Hilfe ;)

**Comment by cluedo10** [comment]
One last question, i created this method:

> @EventHandler
> public void click(Click e) {
> 			ProxiedPlayer p = (ProxiedPlayer) e.getPlayer();
> 			if(e.getInventory().getName().equalsIgnoreCase(Commands.system.getName())) {
> ...........


It is correct ? The event get not fired it doesn't happen anything in the inventory

**Comment by kaerns** [comment]
bungeeutil uses a different api to handle item interaction. you are adding the listeners directly to the specific items.

			ItemStack arrowprev = new ItemStack(Material.ARROW, 1) {
				@Override
				public void click(Click click) {
					click.getPlayer().playSound(SoundEffect.UI_BUTTON_CLICK, SoundCategory.MASTER, click.getPlayer().getLocation(), 0.3F, 1.0F);
					prevPage();
				}};
			arrowprev.getItemMeta().setDisplayName("§6prev page "+(this.currentpage-1));
			inv.setItem(45, arrowprev);

**Comment by cluedo10** [comment]
Irgendwie will es bei mir nicht klappen, bei Spigot hat das System Funktioniert.

> 02:52:15 [SEVERE] java.lang.NullPointerException
02:52:15 [SEVERE] 	at de.leastrio.ts.verifysystem.Commands.Commands.fort(Commands.java:75)
02:52:15 [SEVERE] 	at de.leastrio.ts.verifysystem.Commands.Commands$2.click(Commands.java:51)
02:52:15 [SEVERE] 	at dev.wolveringer.bungeeUtil.packetlib.Handler_v1_8_0.handleInventoryClickPacketSync(Unknown Source)

Es ist ein TS-Verify System, welches mit GUIS gemacht wurde

> Commands(75): if(plugin.getAPI().getClientByNameExact(ts, true) != null) {
> Commands(51): new Commands().fort(e.getPlayer(), Commands.tsverify.get(e.getPlayer().getUniqueId()), System);

**Comment by kaerns** [comment]
Spigot, BungeeCord und BungeeUtil sind komplett verschiedene dinge und man kann nicht so einfach Plugins Kopieren und hoffen das es funktioniert. Solltest du Programmieren können dann wirst du eine so einfache NullPointerException lösen können. Ohne weiteren Kontext kann ich dir nur sagen das vermutlich plugin null ist oder getAPI() null zurückgibt.

**Comment by cluedo10** [comment]
Das Plugin wurde von mir persönlich selbst geschrieben daher weiß ich auch dass es auf Spigot funktioniert, habe mir gedacht über Bungee wäre es besser da es dann Global läuft alles umgeschrieben usw. und geht nur mehr die hälfte das Plugin gibt doch nicht mal mehr Fehlermeldungen aus z.b(wenn der Spieler nicht am Teamspeak Server ist).

**Comment by cluedo10** [comment]
PS: hat sich alles erledigt mit BungeeUtil 2.0 geht alles, ein Fehler bei BungeeUtil(Denke ich) gibt es, und zwar wenn ich lore.add("") mache um eine Leere Zeile in der Lore zu machen steht dort nur so ein komisches null, ich möchte dort aber eine leere Zeile haben

**Comment by WolverinDEV** [comment]
Du musst (auch bei spigot) '§<IrgendeinCode>' hinztufügen.

**Comment by cluedo10** [comment]
Bei Spigot ging das *immer* ohne! Von daher habe ich es so gelassen

**Comment by craftrise** [comment]
@WolverinDEV Will you add a maven repository for version 2.6?

**Comment by WolverinDEV** [comment]
I think this issue/this issues are resolved and this thread could be closed?
