### ISSUE TITLE
Frage zur AnvilGui API

### ISSUE THREAD

**Issue by HydraDE** [WolverinDEV/BungeeUtil#58]
Hallo,

ich habe eine Frage bezüglich der AnvilGui API und zwar ich habe diesen Code:

```
banMenu.setItem(17, ItemBuilder.create().material(Material.ANVIL).amount(1).name("§cEigener Grund").listener((click)->{
			Player p = click.getPlayer();
			AnvilGui gui = new AnvilGui(p);
			gui.setBackgroundMessage("Grund");
			gui.setColorPrefix("§f");
			
			gui.setCenterItem(ItemBuilder.create().material(Material.PAPER).amount(1).name("Grund").listener((click2)->{
				BungeeCord.getInstance().broadcast("§7test1");
			}).build());
			
			gui.setOutputItem(ItemBuilder.create().material(Material.PAPER).amount(1).name("Grund").listener((click3)->{
				BungeeCord.getInstance().broadcast("§7test2");
			}).build());
			
			gui.open();
		}).build());
```
...aber er sendet keine Nachricht, wenn ich auf das Output Item klicke. Was mache ich falsch?
Viele Grüße
HydraDE

**Comment by kaerns** [comment]
Also auf dem ersten blick sehe ich hier keine Fehler, jedoch hab ich auch noch nie den ItemBuilder bei sowas verwendet. Zeigt die Console irgendwelche exceptions an?

**Comment by WolverinDEV** [comment]
Hey,
du kannst natrülich in der Anvil Inventory classe die Item click listener verwenden.
Du musst die classe [AnvilGuiListener](https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/main/java/dev/wolveringer/bungeeutil/inventory/anvil/AnvilGuiListener.java) vewenden (welche du voher beim AnvilGui registrieren musst) (https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/main/java/dev/wolveringer/bungeeutil/inventory/anvil/AnvilGui.java#L234)

**Comment by HydraDE** [comment]
Danke, hat geklappt
