### ISSUE TITLE
Frage zur SkullMeta

### ISSUE THREAD

**Issue by HydraDE** [WolverinDEV/BungeeUtil#59]
Hey, 

könnte mir jemand ein Beispiel für das Erstellen eines Skulls geben?

Viele Grüße
HydraDE

**Comment by kaerns** [comment]
UUID target = *your uuid or something*;		
Item infos = new Item(Material.SKULL_ITEM, 1, (short)3);
		((SkullMeta)infos.getItemMeta()).setSkin(target);
		infos.getItemMeta().setDisplayName("§6"+name);
		infos.getItemMeta().setLore(Arrays.asList("line1", "line2"));
inventory.addItem(infos);

**Comment by HydraDE** [comment]
Ok, danke <3

**Comment by HydraDE** [comment]
Und wie genau addet man da jetzt einen ClickListener?

**Comment by WolverinDEV** [comment]
Wenn du eigende Skins laden willst, rate ich dir mal bei der classe SkinFacroty vorbeizuschauen :)
https://github.com/WolverinDEV/BungeeUtil/wiki/Skin-API
