### ISSUE TITLE
setSkullOwner option

### ISSUE THREAD

**Issue by leolifbom** [WolverinDEV/BungeeUtil#62]
Hey. I'm trying to add a skull item to an inventory with the skin of a player. Please add a setSkullOwner option to the ItemBuilder. If it already exists, can you tell me how to use it?

**Comment by WolverinDEV** [comment]
You could add a post item creator handler and then add to the item meta the skull owner.
But i'll not add this to the basic item builder case its not a method which could be applied for all items
